<?php
require('../PHP/rate.php');
require('../Layout/start.html');
require('../Layout/head.html');
require('../Layout/nav.html');
require('../Layout/rate.html');
require('../Layout/footer.html');
require('../Layout/scripts.html');
require('../Layout/end.html');
